# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92b856b6414ee159f63c051b4b2e04b7bf0d7c6140ea4441020369d92c893a5c2a5e1bce280dd8ff6b9838c7fe54b3e43a1338d5e627855efec3f69885c34539

test:
  secret_key_base: 44909c2a43ad5b858efbcc35ed699b5dd3cde2e39238e16648017f6488d1d3293d313971831336b3d39567fdb9c5dfc5ec70447dc819dcb4563491a8860b2617

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
